### ISSUE TITLE
hash vs hashref in constructor

### ISSUE THREAD

**Issue by berekuk** [throughnothing/Ubic-Service-Starman#1]
Synopsis says that you should pass `{ ... }` hashref in constructor, but it actually expects plain list of options and dies with `Odd number of elements in hash assignment` error.

**Comment by throughnothing** [comment]
Ahh, you are right.  Thanks for the report!

**Comment by berekuk** [comment]
This was actually the report from @flymio who just used your module for one of his websites :)

**Comment by throughnothing** [comment]
@berekuk Actually, looking at this further....this may be a byproduct of incorrect documentation in Ubic::Service::Plack?  I copied the initial documentation from that, and it looks like the docs there say to pass a `{ ... }` and yet it really accepts a plain list of options?  Maybe I'm wrong here, or Params::Validate does some interpretation on it if it's a hashref.  Thoughts?

**Comment by berekuk** [comment]
Exactly, `Params::Validate` supports both styles.

BTW, if you're going to choose only one, please choose hashref style, because `Ubic::ServiceLoader::Ext::ini` and `Ubic::ServiceLoader::Ext::yaml` pass options as hashrefs.

**Comment by throughnothing** [comment]
Ok great, that's what my hunch was, so that eliminates my confusion.  I'll update it to accept a hashref rather than a list of args.  Thanks.  I'll make that change and mint a new release today.

**Comment by throughnothing** [comment]
@berekuk I'd actually like to support both ways, would the easiest way to do that just be to use Params::Validate in my module as well?

**Comment by berekuk** [comment]
I think the easiest way would be to do it manually: `if (@_ > 1) { ... } else { ... }`.
On the other hand, `Params::Validate` would give you clearer error messages, and it's already in dependencies since `Ubic` itself uses it.
In the end, it's your module and your choice :)

**Comment by throughnothing** [comment]
Fixed this, and just released as v0.003.  Thanks again.
